from __future__ import annotations

import ast
import subprocess
import sys
from pathlib import Path

from scripts.build_train_gpt_mlx import SOURCE_MODULES, assemble

REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATED_ROOT = REPO_ROOT / "train_gpt_mlx.py"
DATA_SOURCE = REPO_ROOT / "train_gpt_mlx_src/data.py"
EVAL_SOURCE = REPO_ROOT / "train_gpt_mlx_src/eval.py"
QUANT_SOURCE = REPO_ROOT / "train_gpt_mlx_src/quantization.py"
MODEL_SOURCE = REPO_ROOT / "train_gpt_mlx_src/model.py"
OPTIMIZER_SOURCE = REPO_ROOT / "train_gpt_mlx_src/optimizer.py"
RUNTIME_SOURCE = REPO_ROOT / "train_gpt_mlx_src/_runtime.py"
ORCHESTRATION_SOURCE = REPO_ROOT / "train_gpt_mlx_src/orchestration.py"

DATA_SYMBOLS = {"load_data_shard", "TokenStream", "TokenLoader"}
EVAL_SYMBOLS = {
    "build_sentencepiece_luts",
    "load_validation_tokens",
    "loss_and_grad_chunked",
    "eval_val",
}
QUANT_SYMBOLS = {
    "_np_float32",
    "keep_float_array",
    "quantize_float_array",
    "quantize_state_dict_int8",
    "dequantize_state_dict_int8",
}

MODEL_SYMBOLS = {
    "rms_norm",
    "CastedLinear",
    "RMSNormNoWeight",
    "CausalSelfAttention",
    "MLP",
    "Block",
    "GPT",
}

OPTIMIZER_SYMBOLS = {
    "token_chunks",
    "accumulate_flat_grads",
    "zeropower_newtonschulz5",
    "Muon",
    "SplitOptimizers",
    "clip_grad_tree",
}
ORCHESTRATION_SYMBOLS = {
    "setup_tokenizer_and_validation",
    "build_model_and_optimizers",
    "log_run_config",
    "run_warmup",
    "run_training_loop",
    "finalize_and_validate_roundtrip",
}


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def run_builder(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, "-m", "scripts.build_train_gpt_mlx", *args],
        cwd=REPO_ROOT,
        check=False,
        capture_output=True,
        text=True,
    )


def top_level_def_names(path: Path) -> set[str]:
    module = ast.parse(read_text(path))
    return {
        node.name
        for node in module.body
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
    }


def assert_type_checking_scaffold(module: ast.Module) -> ast.If:
    assert len(module.body) >= 3

    future_import = module.body[0]
    typing_import = module.body[1]
    scaffold_gate = module.body[2]

    assert isinstance(future_import, ast.ImportFrom)
    assert future_import.module == "__future__"
    assert future_import.names[0].name == "annotations"

    assert isinstance(typing_import, ast.ImportFrom)
    assert typing_import.module == "typing"
    assert typing_import.names[0].name == "TYPE_CHECKING"

    assert isinstance(scaffold_gate, ast.If)
    assert isinstance(scaffold_gate.test, ast.Name)
    assert scaffold_gate.test.id == "TYPE_CHECKING"

    top_level_imports = [
        node for node in module.body if isinstance(node, (ast.Import, ast.ImportFrom))
    ]
    assert len(top_level_imports) == 2
    return scaffold_gate


def test_build_train_gpt_mlx_check_exits_zero() -> None:
    result = run_builder("--check")
    assert result.returncode == 0, result.stdout + result.stderr


def test_build_train_gpt_mlx_self_test_exits_zero() -> None:
    result = run_builder("--self-test")
    assert result.returncode == 0, result.stdout + result.stderr


def test_generated_train_gpt_mlx_parses() -> None:
    ast.parse(read_text(GENERATED_ROOT))


def test_generated_train_gpt_mlx_under_line_cap() -> None:
    assert len(read_text(GENERATED_ROOT).splitlines()) < 1500


def test_generated_train_gpt_mlx_has_banner() -> None:
    text = read_text(GENERATED_ROOT)
    assert "generated by scripts/build_train_gpt_mlx.py" in text
    assert "train_gpt_mlx_src/" in text
    assert "Do not hand-edit train_gpt_mlx.py" in text


def test_generated_train_gpt_mlx_preserves_eval_and_proof_strings() -> None:
    text = read_text(GENERATED_ROOT)
    assert "val_progress:{batch_idx}/{total_batches}" in text
    assert "VAL_BATCH_SIZE must provide at least one sequence;" in text
    assert "Validation split is too short for TRAIN_SEQ_LEN=" in text
    assert "serialized_model_int8_zlib" in text
    assert "Total submission size int8+zlib" in text
    assert "final_int8_zlib_roundtrip_exact" in text
    assert "stopping_early: wallclock_cap" in text


def test_generated_train_gpt_mlx_self_reads() -> None:
    assert 'Path(__file__).read_text(encoding="utf-8")' in read_text(GENERATED_ROOT)


def test_generated_train_gpt_mlx_has_no_type_checking_scaffold() -> None:
    text = read_text(GENERATED_ROOT)
    assert "TYPE_CHECKING" not in text
    assert "from typing import TYPE_CHECKING" not in text
    assert "if TYPE_CHECKING:" not in text


def test_generated_train_gpt_mlx_has_no_live_sibling_imports() -> None:
    module = ast.parse(read_text(GENERATED_ROOT))
    sibling_imports = {
        node.module
        for node in module.body
        if isinstance(node, ast.ImportFrom)
        and node.module is not None
        and node.module.startswith("train_gpt_mlx_src")
    }
    sibling_imports.update(
        alias.name
        for node in module.body
        if isinstance(node, ast.Import)
        for alias in node.names
        if alias.name.startswith("train_gpt_mlx_src")
    )
    assert not sibling_imports, sibling_imports


def test_generated_train_gpt_mlx_rebuild_is_byte_idempotent() -> None:
    first_run = run_builder()
    assert first_run.returncode == 0, first_run.stdout + first_run.stderr
    first_bytes = GENERATED_ROOT.read_bytes()

    second_run = run_builder()
    assert second_run.returncode == 0, second_run.stdout + second_run.stderr
    second_bytes = GENERATED_ROOT.read_bytes()

    assert first_bytes == second_bytes, "builder is not byte-idempotent across consecutive rebuilds"


def test_data_fragment_uses_type_checking_scaffold_only() -> None:
    module = ast.parse(read_text(DATA_SOURCE))
    scaffold_gate = assert_type_checking_scaffold(module)

    scaffold_imports = [
        node
        for node in scaffold_gate.body
        if isinstance(node, (ast.Import, ast.ImportFrom))
    ]
    assert any(
        isinstance(node, ast.ImportFrom)
        and node.module == "collections.abc"
        and node.names[0].name == "Callable"
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.ImportFrom)
        and node.module == "pathlib"
        and node.names[0].name == "Path"
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "glob" for alias in node.names)
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "numpy" and alias.asname == "np" for alias in node.names)
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "mlx.core" and alias.asname == "mx" for alias in node.names)
        for node in scaffold_imports
    )

    assert DATA_SYMBOLS.issubset(top_level_def_names(DATA_SOURCE))


def test_optimizer_fragment_uses_type_checking_scaffold_only() -> None:
    module = ast.parse(read_text(OPTIMIZER_SOURCE))
    scaffold_gate = assert_type_checking_scaffold(module)

    scaffold_imports = [
        node
        for node in scaffold_gate.body
        if isinstance(node, (ast.Import, ast.ImportFrom))
    ]
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "math" for alias in node.names)
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "mlx.core" and alias.asname == "mx" for alias in node.names)
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "mlx.optimizers" and alias.asname == "optim" for alias in node.names)
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "numpy" and alias.asname == "np" for alias in node.names)
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.ImportFrom)
        and node.module == "mlx.utils"
        and {alias.name for alias in node.names} == {"tree_flatten", "tree_unflatten"}
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.ImportFrom)
        and node.module == "train_gpt_mlx_src.config"
        and {alias.name for alias in node.names} == {"Hyperparameters"}
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.ImportFrom)
        and node.module == "train_gpt_mlx_src.model"
        and {alias.name for alias in node.names} == {"GPT"}
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.ImportFrom)
        and node.module == "train_gpt_mlx_src.quantization"
        and {alias.name for alias in node.names} == {
            "CONTROL_TENSOR_NAME_PATTERNS",
            "_np_float32",
        }
        for node in scaffold_imports
    )

    assert OPTIMIZER_SYMBOLS.issubset(top_level_def_names(OPTIMIZER_SOURCE))


def test_runtime_no_longer_owns_data_helpers() -> None:
    runtime_defs = top_level_def_names(RUNTIME_SOURCE)
    assert DATA_SYMBOLS.isdisjoint(runtime_defs)


def test_eval_fragment_uses_type_checking_scaffold_only() -> None:
    module = ast.parse(read_text(EVAL_SOURCE))
    scaffold_gate = assert_type_checking_scaffold(module)

    scaffold_imports = [
        node
        for node in scaffold_gate.body
        if isinstance(node, (ast.Import, ast.ImportFrom))
    ]
    assert any(
        isinstance(node, ast.ImportFrom)
        and node.module == "collections.abc"
        and node.names[0].name == "Callable"
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.ImportFrom)
        and node.module == "pathlib"
        and node.names[0].name == "Path"
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "glob" for alias in node.names)
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "math" for alias in node.names)
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "numpy" and alias.asname == "np" for alias in node.names)
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "mlx.core" and alias.asname == "mx" for alias in node.names)
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "sentencepiece" and alias.asname == "spm" for alias in node.names)
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.ImportFrom)
        and node.module == "train_gpt_mlx_src.config"
        and node.names[0].name == "Hyperparameters"
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.ImportFrom)
        and node.module == "train_gpt_mlx_src.data"
        and node.names[0].name == "TokenLoader"
        for node in scaffold_imports
    )

    assert EVAL_SYMBOLS.issubset(top_level_def_names(EVAL_SOURCE))


def test_runtime_no_longer_owns_eval_helpers() -> None:
    runtime_defs = top_level_def_names(RUNTIME_SOURCE)
    assert EVAL_SYMBOLS.isdisjoint(runtime_defs)


def test_runtime_no_longer_owns_optimizer_helpers() -> None:
    runtime_defs = top_level_def_names(RUNTIME_SOURCE)
    assert OPTIMIZER_SYMBOLS.isdisjoint(runtime_defs)
    runtime_text = read_text(RUNTIME_SOURCE)
    assert "def token_chunks(" not in runtime_text
    assert "def accumulate_flat_grads(" not in runtime_text
    assert "def zeropower_newtonschulz5(" not in runtime_text
    assert "class Muon" not in runtime_text
    assert "class SplitOptimizers" not in runtime_text
    assert "def clip_grad_tree(" not in runtime_text


def test_orchestration_fragment_uses_type_checking_scaffold_only() -> None:
    module = ast.parse(read_text(ORCHESTRATION_SOURCE))
    scaffold_gate = assert_type_checking_scaffold(module)

    scaffold_imports = [
        node
        for node in scaffold_gate.body
        if isinstance(node, (ast.Import, ast.ImportFrom))
    ]
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "pickle" for alias in node.names)
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "time" for alias in node.names)
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "zlib" for alias in node.names)
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "numpy" and alias.asname == "np" for alias in node.names)
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "mlx.core" and alias.asname == "mx" for alias in node.names)
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "mlx.nn" and alias.asname == "nn" for alias in node.names)
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "sentencepiece" and alias.asname == "spm" for alias in node.names)
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.ImportFrom)
        and node.module == "collections.abc"
        and {alias.name for alias in node.names} == {"Callable"}
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.ImportFrom)
        and node.module == "pathlib"
        and {alias.name for alias in node.names} == {"Path"}
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.ImportFrom)
        and node.module == "mlx.utils"
        and {alias.name for alias in node.names} == {"tree_flatten", "tree_unflatten"}
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.ImportFrom)
        and node.module == "train_gpt_mlx_src.config"
        and {alias.name for alias in node.names} == {"Hyperparameters"}
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.ImportFrom)
        and node.module == "train_gpt_mlx_src.data"
        and {alias.name for alias in node.names} == {"TokenLoader"}
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.ImportFrom)
        and node.module == "train_gpt_mlx_src.eval"
        and {alias.name for alias in node.names} == {
            "build_sentencepiece_luts",
            "eval_val",
            "load_validation_tokens",
            "loss_and_grad_chunked",
        }
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.ImportFrom)
        and node.module == "train_gpt_mlx_src.quantization"
        and {alias.name for alias in node.names} == {
            "dequantize_state_dict_int8",
            "quantize_state_dict_int8",
        }
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.ImportFrom)
        and node.module == "train_gpt_mlx_src.model"
        and {alias.name for alias in node.names} == {"GPT"}
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.ImportFrom)
        and node.module == "train_gpt_mlx_src.optimizer"
        and {alias.name for alias in node.names} == {
            "SplitOptimizers",
            "accumulate_flat_grads",
            "clip_grad_tree",
        }
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.ImportFrom)
        and node.module == "data.training_manifest"
        and {alias.name for alias in node.names} == {"validate_dataset_tokenizer_pair"}
        for node in scaffold_imports
    )

    assert ORCHESTRATION_SYMBOLS.issubset(top_level_def_names(ORCHESTRATION_SOURCE))


def test_runtime_no_longer_owns_orchestration_helpers() -> None:
    runtime_defs = top_level_def_names(RUNTIME_SOURCE)
    assert ORCHESTRATION_SYMBOLS.isdisjoint(runtime_defs)
    runtime_text = read_text(RUNTIME_SOURCE)
    assert "def setup_tokenizer_and_validation(" not in runtime_text
    assert "def build_model_and_optimizers(" not in runtime_text
    assert "def run_warmup(" not in runtime_text
    assert "def run_training_loop(" not in runtime_text
    assert "def finalize_and_validate_roundtrip(" not in runtime_text


def test_quantization_fragment_uses_type_checking_scaffold_only() -> None:
    module = ast.parse(read_text(QUANT_SOURCE))
    scaffold_gate = assert_type_checking_scaffold(module)

    scaffold_imports = [
        node
        for node in scaffold_gate.body
        if isinstance(node, (ast.Import, ast.ImportFrom))
    ]
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "os" for alias in node.names)
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "mlx.core" and alias.asname == "mx" for alias in node.names)
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "numpy" and alias.asname == "np" for alias in node.names)
        for node in scaffold_imports
    )

    quant_defs = top_level_def_names(QUANT_SOURCE)
    assert QUANT_SYMBOLS.issubset(quant_defs)

    quant_text = read_text(QUANT_SOURCE)
    assert "CONTROL_TENSOR_NAME_PATTERNS = tuple(" in quant_text
    assert "INT8_KEEP_FLOAT_FP32_NAME_PATTERNS = tuple(" in quant_text


def test_runtime_no_longer_owns_quantization_helpers() -> None:
    runtime_text = read_text(RUNTIME_SOURCE)
    runtime_defs = top_level_def_names(RUNTIME_SOURCE)
    assert QUANT_SYMBOLS.isdisjoint(runtime_defs)
    assert "CONTROL_TENSOR_NAME_PATTERNS =" not in runtime_text
    assert "INT8_KEEP_FLOAT_FP32_NAME_PATTERNS =" not in runtime_text
    assert "MX_DTYPE_FROM_NAME =" not in runtime_text


def test_model_fragment_uses_type_checking_scaffold_only() -> None:
    module = ast.parse(read_text(MODEL_SOURCE))
    scaffold_gate = assert_type_checking_scaffold(module)

    scaffold_imports = [
        node
        for node in scaffold_gate.body
        if isinstance(node, (ast.Import, ast.ImportFrom))
    ]
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "mlx.core" and alias.asname == "mx" for alias in node.names)
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "mlx.nn" and alias.asname == "nn" for alias in node.names)
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.Import)
        and any(alias.name == "numpy" and alias.asname == "np" for alias in node.names)
        for node in scaffold_imports
    )
    assert any(
        isinstance(node, ast.ImportFrom)
        and node.module == "train_gpt_mlx_src.config"
        and node.names[0].name == "COMPUTE_DTYPE"
        for node in scaffold_imports
    )
    assert len(scaffold_imports) == 4

    assert MODEL_SYMBOLS.issubset(top_level_def_names(MODEL_SOURCE))


def test_runtime_no_longer_owns_model_helpers() -> None:
    runtime_text = read_text(RUNTIME_SOURCE)
    runtime_defs = top_level_def_names(RUNTIME_SOURCE)
    assert MODEL_SYMBOLS.isdisjoint(runtime_defs)
    assert "def rms_norm(" not in runtime_text

def test_assemble_strips_type_checking_scaffolds() -> None:
    text = assemble()
    assert "TYPE_CHECKING" not in text
    assert "from typing import TYPE_CHECKING" not in text


def test_assemble_is_idempotent() -> None:
    first = assemble().encode("utf-8")
    second = assemble().encode("utf-8")
    assert first == second


def test_assemble_concatenates_in_declared_order() -> None:
    assert SOURCE_MODULES == (
        "train_gpt_mlx_src/config.py",
        "train_gpt_mlx_src/data.py",
        "train_gpt_mlx_src/eval.py",
        "train_gpt_mlx_src/quantization.py",
        "train_gpt_mlx_src/model.py",
        "train_gpt_mlx_src/optimizer.py",
        "train_gpt_mlx_src/orchestration.py",
        "train_gpt_mlx_src/_runtime.py",
    )
    text = assemble()
    assert text.index("class Hyperparameters") < text.index("def load_data_shard")
    assert text.index("def load_data_shard") < text.index("def build_sentencepiece_luts")
    assert text.index("def build_sentencepiece_luts") < text.index(
        "CONTROL_TENSOR_NAME_PATTERNS ="
    )
    assert text.index("CONTROL_TENSOR_NAME_PATTERNS =") < text.index("def rms_norm")
    assert text.index("CONTROL_TENSOR_NAME_PATTERNS =") < text.index("class SplitOptimizers")
    assert text.index("class GPT") < text.index("class SplitOptimizers")
    assert text.index("INT8_KEEP_FLOAT_FP32_NAME_PATTERNS =") < text.index(
        "class SplitOptimizers"
    )
    assert text.index("def quantize_state_dict_int8") < text.index("class SplitOptimizers")
    assert text.index("def dequantize_state_dict_int8") < text.index("class SplitOptimizers")
    assert text.index("def loss_and_grad_chunked") < text.index("def token_chunks")
    assert text.index("def token_chunks") < text.index("def setup_tokenizer_and_validation")
    assert text.index("class SplitOptimizers") < text.index("def setup_tokenizer_and_validation")
    assert text.index("def finalize_and_validate_roundtrip") < text.index("def main()")
    assert text.index("def clip_grad_tree") < text.index("def main()")
