from __future__ import annotations

import argparse
import difflib
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "train_gpt_mlx.py"
SOURCE_MODULES: tuple[str, ...] = (
    "train_gpt_mlx_src/config.py",
    "train_gpt_mlx_src/data.py",
    "train_gpt_mlx_src/eval.py",
    "train_gpt_mlx_src/quantization.py",
    "train_gpt_mlx_src/model.py",
    "train_gpt_mlx_src/optimizer.py",
    "train_gpt_mlx_src/orchestration.py",
    "train_gpt_mlx_src/_runtime.py",
)
MAX_DIFF_LINES = 40
ROOT_PREAMBLE_IMPORTS = {"import math", "import os"}
EXPECTED_DOCSTRING_OPENING = '"""'
BANNER = (
    "# This file is generated by scripts/build_train_gpt_mlx.py from train_gpt_mlx_src/.\n"
    "# Do not hand-edit train_gpt_mlx.py; edit the source modules and rebuild instead."
)
PRESERVED_DOCSTRING = (
    '"""\n'
    "The `train_gpt.py` and `train_gpt_mlx.py` scripts are intended as good launching-off points for new participants, not SOTA configs. We'll accept PRs that tune, improve, or simplify these scripts without significantly increasing complexity, but competitive submissions should stay in the `/records` folder.\n"
    "\n"
    "Hard stop: To keep readable for newcomers, let's make sure `train_gpt.py` and `train_gpt_mlx.py` never are longer than 1500 lines.\n"
    '"""\n'
)


def fail(message: str) -> None:
    print(message, file=sys.stderr)
    raise SystemExit(1)


def validate_constants() -> None:
    required_banner_substrings = (
        "generated by scripts/build_train_gpt_mlx.py",
        "train_gpt_mlx_src/",
        "Do not hand-edit train_gpt_mlx.py",
    )
    for substring in required_banner_substrings:
        if substring not in BANNER:
            fail(f"BANNER is missing required substring: {substring}")
    if not PRESERVED_DOCSTRING.startswith(EXPECTED_DOCSTRING_OPENING):
        fail("PRESERVED_DOCSTRING must start with the expected triple-quoted opening")


def normalize_line_endings(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n")


def collapse_edge_blank_runs(lines: list[str]) -> list[str]:
    start = 0
    while start < len(lines) and lines[start].strip() == "":
        start += 1
    end = len(lines)
    while end > start and lines[end - 1].strip() == "":
        end -= 1
    return lines[start:end]


def strip_standalone_type_checking_scaffold(
    text: str, strip_duplicate_root_imports: bool = False
) -> str:
    lines = text.split("\n")
    if not lines or lines[0] != "from __future__ import annotations":
        return text

    cursor = 1
    while cursor < len(lines) and lines[cursor].strip() == "":
        cursor += 1

    preserved_header: list[str] = []
    while cursor < len(lines) and lines[cursor] != "from typing import TYPE_CHECKING":
        preserved_header.append(lines[cursor])
        cursor += 1
    if cursor >= len(lines):
        return text

    cursor += 1
    while cursor < len(lines) and lines[cursor].strip() == "":
        cursor += 1
    if cursor >= len(lines) or lines[cursor] != "if TYPE_CHECKING:":
        return text

    body_start = cursor + 1
    while body_start < len(lines) and (
        lines[body_start].startswith("    ") or lines[body_start].strip() == ""
    ):
        body_start += 1

    body = lines[body_start:]
    if strip_duplicate_root_imports:
        preserved_header = [
            line for line in preserved_header if line not in ROOT_PREAMBLE_IMPORTS
        ]
    if not preserved_header:
        return "\n".join(body)
    return "\n".join(preserved_header + [""] + body)


def module_body_for(
    relative_path: str,
    repo_root: Path = REPO_ROOT,
    strip_duplicate_root_imports: bool = False,
) -> str:
    source_path = repo_root / relative_path
    if not source_path.is_file():
        fail(f"Missing source module: {relative_path}")
    raw_text = source_path.read_text(encoding="utf-8")
    if raw_text == "":
        fail(f"Source module is empty: {relative_path}")

    # Preserve interior source bytes — including inherited trailing spaces in the
    # seeded monolith — and only normalize line endings plus edge blank runs.
    # Standalone source modules may carry type-only scaffolding for lint/type checks;
    # the generated root omits it because config.py already provides live imports.
    normalized_text = strip_standalone_type_checking_scaffold(
        normalize_line_endings(raw_text),
        strip_duplicate_root_imports=strip_duplicate_root_imports,
    )
    body_lines = collapse_edge_blank_runs(normalized_text.split("\n"))
    body = "\n".join(body_lines)
    if body == "":
        fail(f"Source module is empty after normalization: {relative_path}")
    return body


def assemble(
    repo_root: Path = REPO_ROOT,
    source_modules: tuple[str, ...] = SOURCE_MODULES,
) -> str:
    validate_constants()
    return (
        BANNER
        + "\n"
        + PRESERVED_DOCSTRING
        + "\n"
        + "\n\n".join(
            module_body_for(path, repo_root, strip_duplicate_root_imports=index > 0)
            for index, path in enumerate(source_modules)
        )
        + "\n"
    )


def diff_lines(current_text: str, rebuilt_text: str, output_path: Path) -> list[str]:
    return list(
        difflib.unified_diff(
            current_text.splitlines(keepends=True),
            rebuilt_text.splitlines(keepends=True),
            fromfile=str(output_path),
            tofile="rebuilt/train_gpt_mlx.py",
        )
    )


def print_diff_digest(current_text: str, rebuilt_text: str, output_path: Path) -> None:
    diff = diff_lines(current_text, rebuilt_text, output_path)
    for line in diff[:MAX_DIFF_LINES]:
        sys.stderr.write(line)
    if len(diff) > MAX_DIFF_LINES:
        sys.stderr.write(f"\n... diff truncated after {MAX_DIFF_LINES} lines\n")


def write_output(text: str, output_path: Path = OUTPUT_PATH) -> None:
    temp_path = output_path.with_name(f".{output_path.name}.tmp.{os.getpid()}")
    try:
        temp_path.write_text(text, encoding="utf-8")
        os.replace(temp_path, output_path)
    finally:
        if temp_path.exists():
            temp_path.unlink()


def check_output(text: str, output_path: Path = OUTPUT_PATH) -> None:
    if not output_path.is_file():
        fail(f"Missing generated file: {output_path.relative_to(REPO_ROOT)}")
    current_bytes = output_path.read_bytes()
    expected_bytes = text.encode("utf-8")
    if current_bytes != expected_bytes:
        current_text = current_bytes.decode("utf-8")
        print_diff_digest(current_text, text, output_path)
        fail("train_gpt_mlx.py is out of sync with scripts/build_train_gpt_mlx.py")


def remove_tree(path: Path) -> None:
    if not path.exists():
        return
    for child in sorted(path.rglob("*"), reverse=True):
        if child.is_file() or child.is_symlink():
            child.unlink()
        else:
            child.rmdir()
    path.rmdir()


def expect_exit_one(func, message: str) -> None:
    try:
        func()
    except SystemExit as exc:
        if exc.code != 1:
            raise AssertionError(
                f"{message}: expected exit code 1, got {exc.code}"
            ) from exc
    else:
        raise AssertionError(f"{message}: expected SystemExit(1)")


def run_self_test() -> None:
    scratch = REPO_ROOT / f".build-train-gpt-mlx-self-test-{os.getpid()}"
    remove_tree(scratch)
    train_gpt_src = scratch / "train_gpt_mlx_src"
    output_path = scratch / "train_gpt_mlx.py"
    train_gpt_src.mkdir(parents=True, exist_ok=False)
    try:
        expect_exit_one(
            lambda: assemble(scratch, ("train_gpt_mlx_src/missing.py",)),
            "missing source module",
        )

        empty_source = train_gpt_src / "empty.py"
        empty_source.write_text("", encoding="utf-8")
        expect_exit_one(
            lambda: assemble(scratch, ("train_gpt_mlx_src/empty.py",)),
            "empty source module",
        )

        source_path = train_gpt_src / "_runtime.py"
        source_path.write_text("\nprint('hello from self-test')\n", encoding="utf-8")
        rebuilt = assemble(scratch, ("train_gpt_mlx_src/_runtime.py",))
        output_path.write_text(rebuilt + "# drift\n", encoding="utf-8")
        expect_exit_one(
            lambda: check_output(rebuilt, output_path),
            "check mode drift detection",
        )

        scaffold_source = train_gpt_src / "typed_fragment.py"
        scaffold_source.write_text(
            "from __future__ import annotations\n\n"
            "from typing import TYPE_CHECKING\n\n"
            "if TYPE_CHECKING:\n"
            "    import os\n\n"
            "VALUE = 1\n",
            encoding="utf-8",
        )
        scaffold_rebuilt = assemble(scratch, ("train_gpt_mlx_src/typed_fragment.py",))
        if "TYPE_CHECKING" in scaffold_rebuilt or "from __future__" in scaffold_rebuilt:
            raise AssertionError(
                "standalone TYPE_CHECKING scaffold leaked into assembly"
            )
        if "VALUE = 1" not in scaffold_rebuilt:
            raise AssertionError("typed fragment body missing from assembly")

        live_import_source = train_gpt_src / "typed_live_fragment.py"
        live_import_source.write_text(
            "from __future__ import annotations\n\n"
            "import math\n"
            "from typing import TYPE_CHECKING\n\n"
            "if TYPE_CHECKING:\n"
            "    import os\n\n"
            "VALUE = math.log(2.0)\n",
            encoding="utf-8",
        )
        live_import_rebuilt = assemble(
            scratch, ("train_gpt_mlx_src/typed_live_fragment.py",)
        )
        if (
            "TYPE_CHECKING" in live_import_rebuilt
            or "from __future__" in live_import_rebuilt
        ):
            raise AssertionError(
                "live-import TYPE_CHECKING scaffold leaked into assembly"
            )
        if "import math" not in live_import_rebuilt:
            raise AssertionError("live import missing from typed fragment assembly")
        if "VALUE = math.log(2.0)" not in live_import_rebuilt:
            raise AssertionError("typed live fragment body missing from assembly")

        config_source = train_gpt_src / "config.py"
        config_source.write_text("import math\n", encoding="utf-8")
        duplicate_import_rebuilt = assemble(
            scratch,
            ("train_gpt_mlx_src/config.py", "train_gpt_mlx_src/typed_live_fragment.py"),
        )
        if duplicate_import_rebuilt.count("import math") != 1:
            raise AssertionError("duplicate root import leaked into assembly")
        if "VALUE = math.log(2.0)" not in duplicate_import_rebuilt:
            raise AssertionError("typed live fragment body missing after import dedupe")
    finally:
        remove_tree(scratch)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Deterministically rebuild train_gpt_mlx.py"
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare the rebuilt output against the on-disk train_gpt_mlx.py",
    )
    parser.add_argument(
        "--self-test",
        action="store_true",
        help="Run inline negative self-tests for builder failure paths",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    if args.self_test:
        run_self_test()
        return 0

    rebuilt_text = assemble()
    if args.check:
        check_output(rebuilt_text)
        return 0

    write_output(rebuilt_text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
